
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: gold_stack_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.prod.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  app:
    build: .
    container_name: gold_stack_api
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    depends_on:
      - postgres

  postgres:
    image: pgvector/pgvector:pg16
    container_name: gold_stack_postgres
    env_file:
      - .env.prod
    ports:
      - "5432:5432"