spring:
    datasource:
        password: password
        url: jdbc:postgresql://localhost:5434/gold_stack
        username: postgres
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
    flyway:
      enabled: true