spring:
    application:
        name: gold_stack
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true

management:
    endpoints:
        web:
            exposure:
                include: health,metrics
server:
    port: 8080
